In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from random import randint

filepath = 'ECOMMRecords2020.csv'
data = pd.read_csv(filepath)
data.head()

,OrderDate,RowID,OrderID,ShipMode,CustomerID,Segment,Country,City,State,PostalCode,Region,ProductID,Category,SubCategory,ProductName,Sales,Quantity,Discount,Profit
0,2020-01-01,849,CA-2017-107503,Standard Class,GA-14725,Consumer,United States,Lorain,Ohio,44052,East,FUR-FU-10003878,Furniture,Furnishings,Linden 10 Round Wall Clock Black,48.896,4,0.2,8.5568
1,2020-01-01,4010,CA-2017-144463,Standard Class,SC-20725,Consumer,United States,Los Angeles,California,90036,West,FUR-FU-10001215,Furniture,Furnishings,Howard Miller 11-1/2 Diameter Brentwood Wall C...,474.430,11,0.0,199.2606
2,2020-01-01,6683,CA-2017-154466,First Class,DP-13390,Home Office,United States,Franklin,Wisconsin,53132,Central,OFF-BI-10002012,Office Supplies,Binders,Wilson Jones Easy Flow II Sheet Lifters,3.600,2,0.0,1.7280
3,2020-01-01,8070,CA-2017-151750,Standard Class,JM-15250,Consumer,United States,Huntsville,Texas,77340,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,454.560,5,0.2,-107.9580
4,2020-01-01,8071,CA-2017-151750,Standard Class,JM-15250,Consumer,United States,Huntsville,Texas,77340,Central,FUR-FU-10002116,Furniture,Furnishings,Tenex Carpeted Granite-Look or Clear Contempor...,141.420,5,0.6,-187.3815

In [24]:
df_comps = data.groupby("ProductID")["Sales"].mean().reset_index()
df_comps = df_comps.rename(columns={"Sales": "byggern"})

df_comps.head()

         ProductID     byggern
0  FUR-BO-10000112  825.174000
1  FUR-BO-10000330  241.960000
2  FUR-BO-10000468  108.495333
3  FUR-BO-10000780  365.783600
4  FUR-BO-10001337  308.499000

In [25]:
def fill_dataset(df, competitors, variation_percentage):
    result_df = df.copy()
    
    for competitor in competitors:
        # Create a new column for each competitor
        result_df[competitor] = result_df['byggern'].apply(
            lambda x: x * (1 + np.random.uniform(-variation_percentage/100, variation_percentage/100))
        )
    
    return result_df

In [26]:
competitors = ["bauhaus", "byggmakker", "byggmax", "byggtorget"]
df_comps = fill_dataset(df_comps, competitors, 20)

df_comps

,ProductID,byggern,bauhaus,byggmakker,byggmax,byggtorget
0,FUR-BO-10000112,825.174000,818.469749,829.433917,905.835167,865.976160
1,FUR-BO-10000330,241.960000,287.019892,249.275108,266.910216,256.266202
2,FUR-BO-10000468,108.495333,123.004924,109.690534,118.481507,128.818189
3,FUR-BO-10000780,365.783600,369.228866,436.912973,301.131602,404.022276
4,FUR-BO-10001337,308.499000,296.372912,330.601119,341.337142,329.106458
...,...,...,...,...,...,...
1520,TEC-PH-10004897,23.976000,20.290305,19.882012,22.530499,28.220694
1521,TEC-PH-10004908,67.992000,74.835672,78.154416,54.498578,54.553320
1522,TEC-PH-10004912,219.800000,178.447173,227.446713,244.670716,231.654848
1523,TEC-PH-10004922,160.776000,157.626286,160.549347,141.185875,179.228209
1524,TEC-PH-10004977,587.970000,554.512050,583.352229,540.985992,534.282737